import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

List <Color> colorsList = [
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  HexColor('#ff0054'),
  HexColor('#5a189a'),
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  HexColor('#ff0054'),
  HexColor('#5a189a'),
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  HexColor('#ff0054'),
  HexColor('#5a189a'),
  Colors.purpleAccent,
  Colors.black,
  Colors.blue,
  Colors.yellow,
  Colors.orange,
  Colors.red,
  Colors.teal,
  HexColor('#ff0054'),
  HexColor('#5a189a'),
];